import XCTest
final class ChatFlowTests: XCTestCase {
    @MainActor func testCapturedGeneralAndThemePickers() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--general"]; app.launch()
        XCTAssertTrue(app.buttons["settings.startScreen"].waitForExistence(timeout: 5)); capture("general-captured-controls")
        app.buttons["settings.startScreen"].tap(); XCTAssertTrue(app.buttons["Codex"].waitForExistence(timeout: 3)); XCTAssertTrue(app.buttons["Chat"].exists); XCTAssertFalse(app.buttons["Work"].exists); capture("general-start-screen-menu")
        app.buttons["Codex"].tap(); XCTAssertTrue(app.buttons["settings.startScreen"].label.contains("Codex"))
        app.buttons["settings.model"].tap(); XCTAssertTrue(app.buttons["5.6 Sol"].waitForExistence(timeout: 3)); XCTAssertTrue(app.buttons["5.5"].exists); XCTAssertFalse(app.buttons["GPT-5.6 Sol"].exists); XCTAssertTrue(app.descendants(matching: .any).matching(NSPredicate(format: "label CONTAINS %@", "Choose the model version")).firstMatch.exists); capture("general-model-menu")
        app.buttons["5.6 Sol"].tap(); XCTAssertTrue(app.buttons["settings.model"].label.contains("5.6 Sol")); capture("general-model-selected")
        app.buttons["Back"].tap(); XCTAssertTrue(app.buttons["Close settings"].waitForExistence(timeout: 3))
        func revealAccentRow() {
            for _ in 0..<5 {
                let row = app.buttons["settings.accent"]
                if row.isHittable && row.frame.maxY < app.frame.maxY - 90 { break }
                app.swipeUp()
            }
            XCTAssertLessThan(app.buttons["settings.accent"].frame.maxY, app.frame.maxY - 90)
        }
        revealAccentRow()
        app.buttons["settings.appearance"].tap(); XCTAssertTrue(app.buttons["System"].waitForExistence(timeout: 3)); capture("appearance-menu-dark")
        app.buttons["Light"].tap(); XCTAssertTrue(app.buttons["settings.appearance"].label.contains("Light")); revealAccentRow()
        app.buttons["settings.accent"].tap(); XCTAssertTrue(app.buttons["Blue"].waitForExistence(timeout: 3)); XCTAssertTrue(app.buttons["Black"].exists); capture("accent-menu-light")
        app.buttons["Orange"].tap(); XCTAssertTrue(app.buttons["settings.accent"].label.contains("Orange")); revealAccentRow(); capture("accent-selected-orange")
        app.buttons["settings.accent"].tap(); app.buttons["Blue"].tap()
        app.buttons["settings.appearance"].tap(); app.buttons["Dark"].tap(); revealAccentRow(); capture("appearance-restored-dark")
        app.buttons["Close settings"].tap(); XCTAssertTrue(app.buttons["sidebarButton"].waitForExistence(timeout: 3))
    }
    @MainActor func testSettingsAboutNavigationAndLightDark() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--settings"]; app.launch()
        XCTAssertTrue(app.buttons["Close settings"].waitForExistence(timeout: 5)); XCTAssertTrue(app.staticTexts["alexmorgan"].exists); capture("settings-root-dark")
        let notifications = app.buttons["settings.notifications"], voice = app.buttons["settings.voice"]
        for _ in 0..<5 { if voice.isHittable { break }; app.swipeUp() }
        XCTAssertTrue(notifications.isHittable); XCTAssertTrue(voice.isHittable)
        XCTAssertLessThan(notifications.frame.minY, voice.frame.minY); capture("settings-app-order")
        let about = app.buttons["settings.about"]
        for _ in 0..<5 { if about.isHittable { break }; app.swipeUp() }
        XCTAssertTrue(about.isHittable); about.tap()
        XCTAssertTrue(app.staticTexts["settings.about.version"].waitForExistence(timeout: 3))
        XCTAssertEqual(app.staticTexts["settings.about.version"].label, "1.2026.267 (36747771815)"); capture("about-dark")
        app.buttons["settings.about.terms"].tap(); XCTAssertTrue(app.alerts["Link"].waitForExistence(timeout: 3)); XCTAssertTrue(app.staticTexts["https://example.com/terms"].exists); app.alerts["Link"].buttons["Done"].tap()
        app.buttons["settings.about.privacy"].tap(); XCTAssertTrue(app.alerts["Link"].waitForExistence(timeout: 3)); XCTAssertTrue(app.staticTexts["https://example.com/privacy"].exists); app.alerts["Link"].buttons["Done"].tap()
        app.buttons["Back from About"].tap(); XCTAssertTrue(app.buttons["Close settings"].waitForExistence(timeout: 3))
        app.buttons["Close settings"].tap(); XCTAssertTrue(app.buttons["sidebarButton"].waitForExistence(timeout: 3))
        app.terminate(); app.launchArguments = ["--ui-test", "--light", "--about"]; app.launch()
        XCTAssertTrue(app.staticTexts["settings.about.appName"].waitForExistence(timeout: 5)); XCTAssertEqual(app.staticTexts["settings.about.appName"].label, "ChatGPT for iOS"); capture("about-light")
        app.buttons["Back from About"].tap(); XCTAssertTrue(app.buttons["Close settings"].waitForExistence(timeout: 3)); capture("settings-root-light")
    }
    /// Native integration test. Installs one offline demo widget only when it is absent.
    @MainActor func testNativeWidgetGalleryAndSmallLinks() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        XCUIDevice.shared.press(.home)
        let springboard = XCUIApplication(bundleIdentifier: "com.apple.springboard")
        let existingWidget = springboard.icons.matching(identifier: "Chat UI Demo").matching(NSPredicate(format: "value == %@", "Widget")).firstMatch.exists
        let icon = springboard.icons.matching(identifier: "Chat UI Demo").matching(NSPredicate(format: "value != %@", "Widget")).firstMatch
        XCTAssertTrue(icon.waitForExistence(timeout: 5)); icon.press(forDuration: 1.2)
        springboard.buttons["Edit Home Screen"].tap()
        springboard.buttons["Edit"].tap(); springboard.buttons["Add Widget"].tap()
        springboard.cells["Chat UI Demo"].tap()
        for index in 1...8 {
            XCTAssertTrue(springboard.pageIndicators.matching(NSPredicate(format: "value == %@", "page \(index) of 8")).firstMatch.waitForExistence(timeout: 3))
            capture("widget-gallery-" + String(index))
            if index < 8 { springboard.swipeLeft() }
        }
        if existingWidget { springboard.buttons["close"].tap(); XCUIDevice.shared.press(.home) }
        else {
            for _ in 0..<5 { springboard.swipeRight() }
            springboard.buttons[" Add Widget"].tap()
        }
        if springboard.buttons["Done"].exists { springboard.buttons["Done"].tap() }
        XCTAssertTrue(springboard.buttons["Camera"].firstMatch.waitForExistence(timeout: 5)); capture("widget-small-installed")
        springboard.buttons["Camera"].firstMatch.tap()
        XCTAssertTrue(app.buttons["camera.shutter"].waitForExistence(timeout: 5)); capture("widget-link-camera")
        XCUIDevice.shared.press(.home)
        springboard.buttons["Voice"].firstMatch.tap()
        XCTAssertTrue(app.buttons["voice.start"].waitForExistence(timeout: 5)); capture("widget-link-voice")
        app.buttons["Close voice chooser"].tap()
        XCUIDevice.shared.press(.home)
        springboard.buttons["Ask ChatGPT"].firstMatch.tap()
        XCTAssertTrue(app.buttons["composerPrimaryButton"].waitForExistence(timeout: 5)); XCTAssertFalse(app.buttons["camera.shutter"].exists); capture("widget-link-chat")
    }
    @MainActor func testImagesTemplatesTrendingAndWorkQuestions() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--images"]; app.launch()
        XCTAssertTrue(app.buttons["images.template.poster"].waitForExistence(timeout: 5)); XCTAssertFalse(app.buttons["Send image prompt"].isEnabled); capture("images-templates")
        app.buttons["images.category.Trending"].tap(); XCTAssertTrue(app.buttons["images.template.aerial"].waitForExistence(timeout: 2)); capture("images-trending")
        app.buttons["images.category.Templates"].tap(); app.buttons["images.template.poster"].tap(); capture("images-poster-detail")
        app.buttons["Close image template"].tap(); XCTAssertTrue(app.buttons["images.template.poster"].waitForExistence(timeout: 2))
        app.buttons["images.template.poster"].tap(); app.buttons["images.try"].tap()
        XCTAssertTrue(app.buttons["Stop Work task"].waitForExistence(timeout: 3)); capture("work-task-running")
        app.buttons["Stop Work task"].tap(); XCTAssertTrue(app.staticTexts["work.question.progress"].waitForExistence(timeout: 3)); capture("work-question-first")
        let answer = app.textFields["work.question.draft"]; answer.tap(); answer.typeText("A garden party")
        app.buttons["work.question.next"].tap(); app.buttons["work.question.previous"].tap(); XCTAssertEqual(answer.value as? String, "A garden party")
        app.buttons["work.question.close"].tap(); app.buttons["work.status"].tap(); capture("work-task-trace")
        app.buttons["work.menu"].tap(); app.buttons["Uploaded files"].tap(); XCTAssertTrue(app.staticTexts["Library"].waitForExistence(timeout: 3)); capture("work-task-library")
        app.buttons["Close Work library"].tap(); app.buttons["Back from Work task"].tap()
        XCTAssertTrue(app.buttons["images.template.poster"].waitForExistence(timeout: 3)); XCTAssertFalse(app.buttons["Send image prompt"].isEnabled)
        app.buttons["Dismiss Library notice"].tap(); XCTAssertFalse(app.buttons["Dismiss Library notice"].exists)
    }
    @MainActor func testExploreSitesAndDraft() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["explore.expand"].tap()
        XCTAssertFalse(app.buttons["explore.expand"].exists); XCTAssertTrue(app.buttons["explore.projects"].exists); capture("explore-expanded")
        app.buttons["explore.sites"].tap(); XCTAssertTrue(app.staticTexts["No sites yet"].waitForExistence(timeout: 3)); capture("sites-empty")
        app.buttons["sites.create"].tap(); XCTAssertTrue(app.staticTexts["composer.context"].waitForExistence(timeout: 3))
        XCTAssertEqual(app.textViews["messageComposer"].value as? String, "Create a website that ..."); capture("sites-work-draft")
        app.buttons["sidebarButton"].tap(); XCTAssertTrue(app.buttons["explore.sites"].exists)
        app.buttons["explore.images"].tap(); XCTAssertEqual(app.textFields["images.composer"].value as? String, "Create a website that ..."); capture("images-retained-sites-draft")
    }
    @MainActor func testProjectDraftSettingsAndIcon() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["explore.expand"].tap(); app.buttons["explore.projects"].tap()
        XCTAssertTrue(app.staticTexts["Start your first project"].waitForExistence(timeout: 3)); capture("projects-empty")
        app.buttons["projects.create"].tap(); XCTAssertTrue(app.textFields["projects.name"].waitForExistence(timeout: 3)); let projectName = app.textFields["projects.name"]; expectation(for: NSPredicate { _, _ in projectName.frame.minY < 300 }, evaluatedWith: nil); waitForExpectations(timeout: 3); XCTAssertFalse(app.buttons["projects.submit"].isEnabled); capture("projects-new")
        app.buttons["projects.settings"].tap(); app.buttons["projects.memory.projectOnly"].tap(); capture("projects-memory-selected")
        app.buttons["Done"].tap()
        app.buttons["Choose project icon"].tap(); capture("projects-icon-picker")
        app.buttons["projects.color.Blue"].tap(); app.buttons["projects.icon.brain"].tap(); capture("projects-icon-selected"); app.buttons["Done"].tap()
        let name = app.textFields["projects.name"]; name.tap(); name.typeText("Garden notebook")
        XCTAssertTrue(app.buttons["projects.submit"].isEnabled)
        app.buttons["projects.suggestion.Writing"].tap(); XCTAssertEqual(name.value as? String, "Writing")
        app.buttons["projects.settings"].tap(); app.buttons["Cancel"].tap(); capture("projects-writing-draft")
        app.buttons["Cancel new project"].tap(); XCTAssertTrue(app.staticTexts["Start your first project"].waitForExistence(timeout: 3))
        app.buttons["projects.add"].tap(); XCTAssertFalse(app.buttons["projects.submit"].isEnabled)
    }
    @MainActor func testMediaPickerComposerContextAndViewer() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        let id = "10000000-0000-0000-0000-000000000000"
        app.buttons["attachmentMenu"].tap(); app.buttons["Photos"].tap()
        XCTAssertTrue(app.buttons["photos.item." + id].waitForExistence(timeout: 3)); capture("photos-recent")
        app.buttons["photos.item." + id].tap(); capture("photos-selected")
        app.buttons["photos.add"].tap(); XCTAssertTrue(app.buttons["Remove image Garden notes 1"].waitForExistence(timeout: 3)); capture("image-composer")
        app.buttons["Remove image Garden notes 1"].tap(); XCTAssertFalse(app.buttons["Remove image Garden notes 1"].exists)
        app.buttons["attachmentMenu"].tap(); app.buttons["Photos"].tap(); app.buttons["photos.item." + id].tap(); app.buttons["photos.add"].tap()
        app.buttons["composerPrimaryButton"].tap(); app.buttons["composerPrimaryButton"].tap()
        let media = app.buttons["message.media." + id]; XCTAssertTrue(media.waitForExistence(timeout: 3)); XCTAssertFalse(media.label.hasPrefix("Play video")); XCTAssertEqual(media.frame.width, 185, accuracy: 1); capture("sent-image")
        media.press(forDuration: 0.8); XCTAssertTrue(app.buttons["Copy"].waitForExistence(timeout: 3)); XCTAssertFalse(app.buttons["Edit"].exists); capture("sent-image-context"); app.buttons["Copy"].tap()
        media.tap(); XCTAssertTrue(app.buttons["media.close"].waitForExistence(timeout: 3)); capture("sent-image-viewer")
        app.buttons["media.options"].tap(); capture("sent-image-viewer-menu"); app.buttons["Add to Favorites"].tap()
        app.buttons["media.image"].firstMatch.tap(); XCTAssertFalse(app.buttons["media.close"].exists); capture("sent-image-viewer-hidden")
        app.buttons["media.image"].firstMatch.tap(); XCTAssertTrue(app.buttons["media.close"].exists); app.buttons["media.close"].tap()
        media.tap(); app.buttons["media.options"].tap(); XCTAssertTrue(app.buttons["Remove from Favorites"].waitForExistence(timeout: 3))
    }
    @MainActor func testVideoPickerAndViewer() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        let id = "20000000-0000-0000-0000-000000000000"
        app.buttons["attachmentMenu"].tap(); app.buttons["Photos"].tap()
        app.swipeUp()
        let video = app.buttons["photos.item." + id]; XCTAssertTrue(video.waitForExistence(timeout: 3)); video.tap()
        XCTAssertEqual(app.buttons["photos.add"].label, "Add 1 video"); capture("photos-video-selected")
        app.buttons["photos.add"].tap(); XCTAssertEqual(app.descendants(matching: .any)["composer.media." + id].firstMatch.value as? String, "0:08"); capture("video-composer")
        app.buttons["composerPrimaryButton"].tap(); app.buttons["composerPrimaryButton"].tap()
        let sentVideo = app.buttons["message.media." + id]
        XCTAssertEqual(sentVideo.label, "Play video Garden clip"); XCTAssertEqual(sentVideo.frame.width, 120, accuracy: 1); XCTAssertEqual(sentVideo.frame.height, 240, accuracy: 1)
        capture("video-sent"); sentVideo.tap(); XCTAssertTrue(app.buttons["media.video.fit"].waitForExistence(timeout: 3))
        XCTAssertFalse(app.buttons["media.options"].exists); XCTAssertFalse(app.buttons["media.tool.Edit"].exists); capture("video-viewer")
        app.buttons["media.video.fit"].tap(); app.buttons["media.close"].tap()
        XCTAssertTrue(app.buttons["message.media." + id].waitForExistence(timeout: 3))
        sentVideo.press(forDuration: 0.8)
        XCTAssertTrue(app.buttons["media.video.fit"].waitForExistence(timeout: 3)); XCTAssertFalse(app.buttons["Copy"].exists)
        capture("video-long-press-viewer")
    }
    @MainActor func testRoundedInlineCodeSelectionAndLinkBothAppearances() {
        let app = XCUIApplication()
        for appearance in ["dark", "light"] {
            app.launchArguments = ["--ui-test", "--inline-code"] + (appearance == "light" ? ["--light"] : [])
            app.launch()
            let text = app.textViews["markdown.inlineCode"].firstMatch
            XCTAssertTrue(text.waitForExistence(timeout: 5))
            XCTAssertTrue((text.value as? String ?? "").contains("Use print(\"Hello!\") as a code example."))
            capture("inline-code-" + appearance)
            text.coordinate(withNormalizedOffset: CGVector(dx: 0.20, dy: 0.13)).press(forDuration: 0.8)
            XCTAssertTrue(app.menuItems["Copy"].waitForExistence(timeout: 3))
            capture("inline-code-selection-" + appearance)
            app.menuItems["Copy"].tap()
            let link = app.links["garden guide"]
            XCTAssertTrue(link.waitForExistence(timeout: 3)); link.tap()
            XCTAssertTrue(app.alerts["Link"].waitForExistence(timeout: 3))
            XCTAssertTrue(app.staticTexts["https://example.com/garden-guide"].exists)
            app.alerts["Link"].buttons["Done"].tap()
            app.terminate()
        }
    }
    @MainActor func testTableCodeAlignmentWrappingSelectionAndScrollBothAppearances() {
        let app = XCUIApplication()
        for appearance in ["dark", "light"] {
            app.launchArguments = ["--ui-test", "--table-code"] + (appearance == "light" ? ["--light"] : [])
            app.launch()
            func cell(_ value: String) -> XCUIElement { app.textViews.matching(NSPredicate(format: "value == %@", value)).firstMatch }
            let mint = cell("mint guide"), water = cell("water_seedlings_gently"), sun = cell("morning_sunlight")
            XCTAssertTrue(mint.waitForExistence(timeout: 5)); XCTAssertTrue(water.exists); XCTAssertTrue(sun.exists)
            XCTAssertLessThan(mint.frame.midX, water.frame.midX); XCTAssertLessThan(water.frame.midX, sun.frame.midX)
            XCTAssertGreaterThan(water.frame.height, cell("basil").frame.height)
            capture("table-code-" + appearance)
            mint.coordinate(withNormalizedOffset: CGVector(dx: 0.2, dy: 0.2)).press(forDuration: 0.8)
            XCTAssertTrue(app.menuItems["Copy"].waitForExistence(timeout: 3)); capture("table-code-selection-" + appearance); app.menuItems["Copy"].tap()
            app.links["guide"].tap(); XCTAssertTrue(app.alerts["Link"].waitForExistence(timeout: 3)); app.alerts["Link"].buttons["Done"].tap()
            let wide = app.scrollViews.matching(identifier: "markdown.table").element(boundBy: 1)
            let last = cell("eight")
            XCTAssertGreaterThan(last.frame.maxX, app.frame.maxX)
            wide.swipeLeft()
            XCTAssertLessThanOrEqual(last.frame.maxX, app.frame.maxX)
            XCTAssertTrue(last.isHittable); capture("table-code-scrolled-" + appearance)
            app.terminate()
        }
    }
    @MainActor func testMarkdownCodeLinkAndSelection() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--markdown"]; app.launch()
        XCTAssertTrue(app.staticTexts["Garden notes"].waitForExistence(timeout: 3)); capture("markdown-heading-list")
        app.swipeUp(); XCTAssertTrue(app.buttons["markdown.code.copy"].waitForExistence(timeout: 3)); capture("markdown-code-table")
        app.buttons["markdown.code.copy"].tap(); XCTAssertEqual(app.buttons["markdown.code.copy"].label, "Code copied")
        let link = app.links["garden guide"]; XCTAssertTrue(link.waitForExistence(timeout: 3)); link.tap()
        XCTAssertTrue(app.alerts["Link"].waitForExistence(timeout: 3)); XCTAssertTrue(app.staticTexts["https://example.com/garden-guide"].exists); app.buttons["Done"].tap()
        app.staticTexts["markdown.code.content"].press(forDuration: 0.8); capture("markdown-code-selection")
        XCTAssertTrue(app.menuItems["Copy"].waitForExistence(timeout: 3))
    }
    @MainActor func testSpaceTabsSearchImageAndFavorites() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["Space"].tap()
        XCTAssertTrue(app.buttons["Space options"].waitForExistence(timeout: 3)); capture("space-suggested")
        app.buttons["space.tab.Favorites"].tap(); XCTAssertTrue(app.staticTexts["Save your favorites"].exists); capture("space-favorites-empty")
        app.buttons["space.tab.Suggested"].tap(); app.buttons["Space options"].tap(); app.buttons["List"].tap(); capture("space-list")
        let search = app.textFields["space.search"]; search.tap(); search.typeText("Garden")
        XCTAssertFalse(app.buttons["Planting guide"].exists)
        app.buttons.matching(NSPredicate(format: "label CONTAINS %@ AND identifier BEGINSWITH %@", "Garden design", "space.item.")).firstMatch.tap()
        XCTAssertTrue(app.buttons["Close Space image"].waitForExistence(timeout: 3)); capture("space-image")
        app.buttons["Space image options"].tap(); app.buttons["Add to Favorites"].tap(); app.buttons["Close Space image"].tap()
        app.buttons["space.tab.Favorites"].tap(); XCTAssertFalse(app.staticTexts["Save your favorites"].exists); capture("space-favorites")
        app.buttons["Space options"].tap(); app.buttons["Filter"].tap(); capture("space-filters")
        app.buttons["PDFs"].tap(); XCTAssertTrue(app.staticTexts["No results"].waitForExistence(timeout: 3))
    }
    @MainActor func testDotNativeTextSelection() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--dot-summary"]; app.launch()
        app.staticTexts.matching(NSPredicate(format: "label BEGINSWITH %@", "One last reminder:")).firstMatch.press(forDuration: 0.8)
        app.buttons["Select text"].tap()
        let selected = app.textViews.matching(NSPredicate(format: "identifier BEGINSWITH %@", "dot.message.")).firstMatch
        XCTAssertTrue(selected.waitForExistence(timeout: 3)); capture("dot-selection-before-touch")
        XCTAssertTrue(app.menuItems["Copy"].waitForExistence(timeout: 3)); app.menuItems["Copy"].tap(); capture("dot-selection-after-copy")
    }
    @MainActor func testDotConnectedSummarySelectionAndPreview() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--dot-connected"]; app.launch()
        XCTAssertTrue(app.staticTexts["0:38"].waitForExistence(timeout: 3)); capture("dot-connected-full")
        XCTAssertEqual(app.buttons["Mute dot call"].value as? String, "Off")
        app.buttons["Mute dot call"].tap(); XCTAssertEqual(app.buttons["Mute dot call"].value as? String, "On"); capture("dot-connected-muted")
        app.buttons["Minimize dot call"].tap(); capture("dot-connected-minimized")
        app.buttons["Expand dot call"].tap(); app.buttons["End dot call"].tap()
        XCTAssertTrue(app.buttons["dot.menu"].waitForExistence(timeout: 3)); XCTAssertFalse(app.staticTexts["Call ended"].exists)
        let assistant = app.staticTexts.matching(NSPredicate(format: "label BEGINSWITH %@", "One last reminder:")).firstMatch
        assistant.press(forDuration: 0.8); app.buttons["Select text"].tap()
        XCTAssertTrue(app.textViews.matching(NSPredicate(format: "identifier BEGINSWITH %@", "dot.message.")).firstMatch.waitForExistence(timeout: 3)); capture("dot-native-selection")
        XCTAssertTrue(app.menuItems["Copy"].waitForExistence(timeout: 3))
        app.terminate(); app.launchArguments = ["--ui-test", "--dot-summary"]; app.launch()
        XCTAssertTrue(app.staticTexts["7:23 · Call ended"].waitForExistence(timeout: 3)); XCTAssertTrue(app.staticTexts["Delivered"].exists); capture("dot-call-summary-delivered")
        app.staticTexts["7:23 · Call ended"].press(forDuration: 0.8)
        XCTAssertTrue(app.buttons["Copy"].waitForExistence(timeout: 3)); XCTAssertTrue(app.buttons["Reply"].exists); XCTAssertFalse(app.buttons["Select text"].exists); capture("dot-call-summary-menu")
        app.buttons["Reply"].tap(); app.buttons["Cancel dot reply"].tap()
        app.terminate(); app.launchArguments = ["--ui-test", "--dot-summary", "--dot-read"]; app.launch()
        XCTAssertTrue(app.staticTexts["Read"].waitForExistence(timeout: 3)); XCTAssertFalse(app.staticTexts["Delivered"].exists); capture("dot-call-summary-read")
        app.terminate(); app.launchArguments = ["--ui-test", "--dot-connected", "--dot-system-preview"]; app.launch()
        XCTAssertTrue(app.buttons["Mute system call preview"].waitForExistence(timeout: 3)); capture("dot-system-call-previews")
        app.buttons["Mute system call preview"].tap(); XCTAssertEqual(app.buttons["Mute system call preview"].value as? String, "On"); capture("dot-system-call-previews-muted")
    }
    @MainActor func testVoiceChooserSessionSettingsAndEnd() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["composerPrimaryButton"].tap()
        XCTAssertTrue(app.buttons["voice.start"].waitForExistence(timeout: 3)); capture("voice-chooser")
        app.buttons["Close voice chooser"].tap()
        XCTAssertTrue(app.buttons["composerPrimaryButton"].waitForExistence(timeout: 3)); app.buttons["composerPrimaryButton"].tap()
        app.buttons["voice.start"].tap()
        XCTAssertTrue(app.buttons["voice.settings"].waitForExistence(timeout: 3)); capture("voice-idle")
        app.buttons["Voice sidebar"].tap(); XCTAssertTrue(app.buttons["voice.end"].exists)
        app.buttons["Voice attachments"].tap(); XCTAssertTrue(app.buttons["Camera"].waitForExistence(timeout: 3)); app.coordinate(withNormalizedOffset: CGVector(dx: 0.8, dy: 0.3)).tap()
        app.buttons["voice.mute"].tap(); XCTAssertEqual(app.buttons["voice.mute"].label, "Mute voice")
        app.buttons["voice.mute"].tap()
        app.buttons["voice.settings"].tap(); capture("voice-settings")
        app.buttons["Voice language"].tap(); capture("voice-language")
        app.buttons["Afrikaans"].tap()
        app.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.2)).tap()
        app.buttons["voice.end"].tap()
        XCTAssertTrue(app.buttons["composerPrimaryButton"].waitForExistence(timeout: 3))
        app.buttons["composerPrimaryButton"].tap()
        XCTAssertTrue(app.buttons["voice.settings"].waitForExistence(timeout: 3)); XCTAssertFalse(app.buttons["voice.start"].exists)
        app.buttons["voice.end"].tap()
    }
    @MainActor func testVoiceTranscriptSharingAndLiveCamera() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["composerPrimaryButton"].tap(); app.buttons["voice.start"].tap()
        app.buttons["Voice thinking"].tap(); capture("voice-effort")
        app.buttons["Voice effort position 2"].tap()
        app.buttons["Voice effort position 2"].press(forDuration: 0.1, thenDragTo: app.buttons["Voice effort position 3"])
        capture("voice-effort-after-drag"); XCTAssertTrue(app.staticTexts["High"].exists)
        app.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.25)).tap()
        let field = app.textFields["voice.composer"]; field.tap(); field.typeText("Help me plan a garden.\n")
        XCTAssertTrue(app.staticTexts["Help me plan a garden."].waitForExistence(timeout: 3)); capture("voice-transcript")
        field.tap(); capture("voice-transcript-keyboard")
        app.buttons["Voice attachments"].tap(); capture("voice-attachments")
        app.buttons["More"].tap(); capture("voice-more")
        app.buttons["Share screen"].tap()
        XCTAssertTrue(app.buttons["voice.shareContinue"].waitForExistence(timeout: 3)); capture("voice-model-switch")
        app.buttons["Cancel voice model switch"].tap(); XCTAssertFalse(app.buttons["voice.sharing"].exists)
        app.buttons["Voice attachments"].tap(); app.buttons["More"].tap(); app.buttons["Share screen"].tap()
        app.buttons["voice.shareContinue"].tap()
        XCTAssertTrue(app.buttons["voice.sharing"].waitForExistence(timeout: 3)); XCTAssertFalse(app.buttons["voice.settings"].exists); capture("voice-sharing")
        app.buttons["Voice attachments"].tap(); capture("voice-stop-sharing-menu")
        app.buttons.matching(NSPredicate(format: "label == %@ AND identifier != %@", "Stop sharing screen", "voice.sharing")).firstMatch.tap(); XCTAssertFalse(app.buttons["voice.sharing"].exists)
        app.buttons["Voice attachments"].tap(); app.buttons["Live video"].tap()
        XCTAssertTrue(app.buttons["Close live camera"].waitForExistence(timeout: 3)); capture("voice-live-camera")
        app.buttons["Flip live camera"].tap(); app.buttons["Live camera flash"].tap(); app.buttons["Close live camera"].tap()
        XCTAssertTrue(app.staticTexts["Help me plan a garden."].exists)
        app.buttons["voice.end"].tap(); XCTAssertTrue(app.buttons["composerPrimaryButton"].waitForExistence(timeout: 3))
    }
    @MainActor func testCodexTaskAndConnectionFlow() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["Codex"].tap()
        XCTAssertTrue(app.buttons["codex.menu"].waitForExistence(timeout: 3)); capture("codex-home")
        app.buttons["New Codex task"].tap()
        let field = app.textFields["codex.composer"]; field.tap(); field.typeText("Create a garden guide")
        app.buttons["Send Codex message"].tap(); XCTAssertTrue(app.buttons["Stop Codex task"].waitForExistence(timeout: 3)); capture("codex-running")
        app.buttons["Stop Codex task"].tap(); field.tap(); field.typeText("Add a planting checklist")
        app.buttons["Send Codex message"].tap(); app.buttons["Stop Codex task"].tap()
        app.buttons["Back to Codex"].tap(); XCTAssertTrue(app.buttons.matching(NSPredicate(format: "label CONTAINS %@", "Create a garden guide")).firstMatch.waitForExistence(timeout: 3))
        app.buttons["codex.menu"].tap(); capture("codex-menu"); app.buttons["Settings"].tap(); capture("codex-settings")
        app.buttons["Close Codex settings"].tap(); app.buttons["codex.menu"].tap(); app.buttons["Add connection"].tap()
        XCTAssertTrue(app.buttons["Pair manually instead"].waitForExistence(timeout: 3)); capture("codex-scanner")
        app.buttons["Pair manually instead"].tap()
        let code = app.textFields["codex.pairing-code"]; XCTAssertTrue(code.waitForExistence(timeout: 3))
        code.tap(); code.typeText("SAMPLE-CODE"); capture("codex-manual-pairing")
        app.buttons["Cancel"].tap(); app.buttons["Close connection scanner"].tap()
    }
    @MainActor func testDotSendReplyCallAndComputer() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["Your dot"].tap()
        XCTAssertTrue(app.buttons["dot.menu"].waitForExistence(timeout: 3)); capture("dot-home")
        let field = app.textFields["dot.composer"]; field.tap(); field.typeText("Please review the garden checklist.")
        app.buttons["Send dot message"].tap()
        XCTAssertTrue(app.staticTexts["Please review the garden checklist."].waitForExistence(timeout: 3))
        app.staticTexts["Please review the garden checklist."].press(forDuration: 0.8)
        XCTAssertTrue(app.buttons["Reply"].waitForExistence(timeout: 3)); capture("dot-message-menu"); app.buttons["Reply"].tap()
        field.tap(); field.typeText("Keep this draft")
        app.buttons["Cancel dot reply"].tap(); XCTAssertTrue((field.value as? String ?? "").contains("Keep this draft"))
        app.buttons["Call dot"].tap()
        expectation(for: NSPredicate(format: "exists == false"), evaluatedWith: app.keyboards.firstMatch); waitForExpectations(timeout: 3)
        capture("dot-calling")
        app.buttons["End dot call"].tap(); XCTAssertTrue(app.buttons["dot.menu"].waitForExistence(timeout: 3))
        app.buttons["dot.menu"].tap(); capture("dot-menu")
        app.buttons["Your dot’s computer"].tap(); XCTAssertTrue(app.buttons["Close dot computer"].waitForExistence(timeout: 3)); capture("dot-computer")
        app.buttons["Show computer keyboard"].tap(); capture("dot-computer-keyboard")
        app.buttons["Close dot computer"].tap(); XCTAssertTrue((field.value as? String ?? "").contains("Keep this draft"))
    }
    @MainActor func testFailedDotCallAndClassicVoiceEndpoints() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--dot-failed"]; app.launch()
        XCTAssertTrue(app.staticTexts["Call failed"].waitForExistence(timeout: 3)); capture("dot-failed-minimized")
        app.buttons["Try again"].tap(); XCTAssertTrue(app.staticTexts["Calling…"].waitForExistence(timeout: 3)); capture("dot-calling-minimized")
        app.buttons["End dot call"].tap(); XCTAssertTrue(app.buttons["dot.menu"].waitForExistence(timeout: 3))
        app.terminate(); app.launchArguments = ["--ui-test", "--voice-classic"]; app.launch()
        XCTAssertTrue(app.buttons["voice.end"].waitForExistence(timeout: 3)); XCTAssertFalse(app.buttons["voice.settings"].exists); capture("voice-classic-idle")
        app.buttons["Voice attachments"].tap(); app.buttons["Share screen"].tap()
        XCTAssertTrue(app.buttons["voice.sharing"].waitForExistence(timeout: 3)); capture("voice-classic-idle-sharing")
        app.buttons["voice.end"].tap(); XCTAssertTrue(app.buttons["composerPrimaryButton"].waitForExistence(timeout: 3))
    }
    @MainActor func testEmptyFeatureDataHasNoSampleFallback() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--empty-finance"]; app.launch()
        XCTAssertTrue(app.buttons["Finance menu"].waitForExistence(timeout: 3))
        XCTAssertFalse(app.staticTexts["Housing"].exists); XCTAssertFalse(app.staticTexts["October"].exists)
        app.buttons["Accounts"].tap(); XCTAssertFalse(app.staticTexts["EVERYDAY SAVINGS"].exists)
        app.buttons["Chats"].tap(); XCTAssertFalse(app.staticTexts["Review sample balances"].exists)
        app.buttons["Transactions"].tap(); XCTAssertFalse(app.staticTexts["Example employer"].exists)
        app.terminate(); app.launchArguments = ["--ui-test", "--empty-health"]; app.launch()
        XCTAssertTrue(app.buttons["Health menu"].waitForExistence(timeout: 3)); XCTAssertFalse(app.staticTexts["Step count"].exists)
        app.buttons["Accounts"].tap(); XCTAssertFalse(app.staticTexts["Connected"].exists)
        app.buttons["health.add-account"].tap(); XCTAssertTrue(app.textFields["health.provider-search"].waitForExistence(timeout: 3))
        XCTAssertFalse(app.staticTexts["Apple Health"].exists); XCTAssertFalse(app.staticTexts["Function Health"].exists)
    }
    @MainActor func testHealthFeatureSetupAndDestinations() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["Customize"].tap(); app.buttons["settings.row.Health"].tap()
        XCTAssertTrue(app.buttons["health.startSetup"].waitForExistence(timeout: 3)); capture("health-introduction")
        app.buttons["health.startSetup"].tap(); capture("health-setup-accounts")
        app.buttons["health.setupContinue"].tap(); capture("health-setup-conditions")
        app.buttons["Skip for now"].tap(); app.buttons["Skip for now"].tap(); app.buttons["Done"].tap()
        XCTAssertTrue(app.buttons["Health menu"].waitForExistence(timeout: 3)); capture("health-home")
        app.buttons["Records"].tap(); capture("health-records"); app.buttons["Chats"].tap(); capture("health-chats")
        app.buttons["Accounts"].tap(); capture("health-accounts"); app.buttons["health.add-account"].tap(); capture("health-providers")
    }
    @MainActor func testFinanceAccountAndDashboardFlow() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["Customize"].tap(); app.buttons["settings.row.Finances"].tap()
        XCTAssertTrue(app.buttons["Finance menu"].waitForExistence(timeout: 3)); capture("finance-dashboard")
        app.buttons["Accounts"].tap(); capture("finance-accounts"); app.buttons["Add account"].tap(); capture("finance-add-account")
        app.buttons["Manual accounts"].tap(); app.buttons["finance.manual.Cash"].tap()
        XCTAssertTrue(app.buttons["Back to finances"].waitForExistence(timeout: 3)); capture("finance-cash-chat"); app.buttons["Back to finances"].tap()
        app.buttons["Transactions"].tap(); app.buttons["Filter transactions"].tap(); capture("finance-filters")
        app.buttons["finance.filter.dates"].tap(); app.buttons["finance.filter.date.Last month"].tap()
        app.buttons["Finance menu"].tap(); app.buttons["Customize dashboard"].tap(); capture("finance-customize")
        app.buttons["Cancel dashboard customization"].tap()
    }
    @MainActor func testPluginPermissionAndTryInChat() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["Settings"].tap(); app.buttons["Plugins"].tap()
        XCTAssertTrue(app.buttons["plugins.row.gmail"].waitForExistence(timeout: 3)); capture("plugins")
        app.buttons["plugins.row.gmail"].tap(); capture("plugin-detail")
        app.buttons["plugins.settings"].tap(); app.buttons["plugins.permissions"].tap(); capture("plugin-permissions")
        app.buttons["plugins.permission.Allow read actions"].tap()
        XCTAssertTrue(app.buttons["plugins.resetPermission"].isEnabled)
        app.buttons["plugins.resetPermission"].tap()
        XCTAssertFalse(app.buttons["plugins.resetPermission"].isEnabled)
        app.buttons["Back"].tap(); app.buttons["Back"].tap(); app.buttons["plugins.tryInChat"].tap()
        XCTAssertTrue(app.textViews["messageComposer"].waitForExistence(timeout: 3))
        XCTAssertTrue((app.textViews["messageComposer"].value as? String ?? "").contains("@Gmail"))
    }
    @MainActor func testMemorySummaryAndAbout() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["Settings"].tap(); app.buttons["Memory"].tap()
        XCTAssertTrue(app.buttons["memory.options"].waitForExistence(timeout: 3)); capture("memory")
        app.buttons["memory.options"].tap(); app.buttons["About memory"].tap()
        XCTAssertTrue(app.buttons["memory.gotIt"].waitForExistence(timeout: 3)); capture("memory-about")
        app.buttons["memory.gotIt"].tap(); app.buttons["memory.options"].tap(); app.buttons["Refresh summary"].tap()
        XCTAssertTrue(app.staticTexts.matching(NSPredicate(format: "label CONTAINS %@", "Updated just now")).firstMatch.waitForExistence(timeout: 3))
        app.buttons["Back"].tap(); XCTAssertTrue(app.buttons["Close settings"].waitForExistence(timeout: 3))
    }
    @MainActor func testCameraEndpoints() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["attachmentMenu"].tap(); app.buttons["Camera"].tap()
        XCTAssertTrue(app.buttons["Camera options"].waitForExistence(timeout: 3)); capture("camera-compact")
        app.buttons["Camera options"].tap(); capture("camera-expanded")
        XCTAssertEqual(app.buttons["camera.flash"].label, "Flash off")
        app.buttons["camera.flash"].tap(); XCTAssertEqual(app.buttons["camera.flash"].label, "Flash auto")
        app.buttons["camera.flash"].tap(); XCTAssertEqual(app.buttons["camera.flash"].label, "Flash on")
        app.buttons["Scan document"].tap(); capture("camera-scan")
        XCTAssertTrue(app.buttons["Finish scan"].exists)
        app.buttons["Camera back"].tap(); XCTAssertTrue(app.buttons["Camera options"].exists)
        app.buttons["Camera back"].tap(); XCTAssertFalse(app.buttons["Camera options"].exists)
        app.buttons["attachmentMenu"].tap(); app.buttons["Camera"].tap()
        expectation(for: NSPredicate(format: "hittable == true"), evaluatedWith: app.buttons["Camera options"])
        waitForExpectations(timeout: 3)
        app.buttons["Camera options"].tap(); app.buttons["Scan document"].tap()
        app.buttons["camera.shutter"].tap(); app.buttons["Finish scan"].tap()
        XCTAssertTrue(app.staticTexts["Scanned document.pdf"].waitForExistence(timeout: 3))
    }
    @MainActor func testSearchAndScheduledPersistence() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        app.buttons["sidebarButton"].tap(); app.buttons["Search chats"].tap()
        let search = app.textFields["search.input"]; XCTAssertTrue(search.waitForExistence(timeout: 3)); search.tap(); search.typeText("design")
        app.buttons["search.category.Images"].tap(); capture("search-images")
        app.buttons["Clear search"].tap(); app.buttons["Close search"].tap()
        app.buttons["Scheduled"].tap(); XCTAssertTrue(app.buttons["schedule.new"].waitForExistence(timeout: 3)); capture("scheduled")
        app.buttons["schedule.new"].tap()
        XCTAssertTrue(app.buttons["Cancel task"].waitForExistence(timeout: 3)); app.buttons["Cancel task"].tap()
        XCTAssertFalse(app.staticTexts["Fixture task"].exists)
        app.buttons["schedule.new"].tap()
        let title = app.textFields["schedule.title"]; XCTAssertTrue(title.waitForExistence(timeout: 3)); title.tap(); title.typeText("Fixture task")
        let instructions = app.textViews["schedule.instructions"]; instructions.tap(); instructions.typeText("Summarize design notes")
        app.buttons["schedule.save"].tap(); XCTAssertTrue(app.staticTexts["Fixture task"].waitForExistence(timeout: 3))
        app.buttons["Open sidebar"].tap(); app.buttons["New chat"].tap()
        app.buttons["sidebarButton"].tap(); app.buttons["Scheduled"].tap()
        XCTAssertTrue(app.staticTexts["Fixture task"].waitForExistence(timeout: 3))
    }
    @MainActor func testReferenceScreenshots() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        XCTAssertTrue(app.buttons["attachmentMenu"].waitForExistence(timeout: 5))
        XCTAssertLessThanOrEqual(app.textViews["messageComposer"].frame.height, 32)
        capture("home")
        app.buttons["attachmentMenu"].tap(); capture("attachment-menu")
        app.tap()
        app.buttons["sidebarButton"].tap(); capture("sidebar")
        app.buttons["Settings"].tap(); capture("settings")
    }
    @MainActor func testConversationFeedbackAndDictation() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--conversation"]; app.launch()
        XCTAssertTrue(app.buttons["Good response"].waitForExistence(timeout: 5)); capture("conversation-dark")
        app.buttons["Good response"].tap()
        XCTAssertFalse(app.buttons["Bad response"].exists)
        app.buttons["Good response"].tap(); XCTAssertTrue(app.buttons["Bad response"].exists)
        app.buttons["Bad response"].tap()
        XCTAssertTrue(app.buttons["Close feedback"].waitForExistence(timeout: 3)); capture("feedback")
        app.buttons["Close feedback"].tap()
        XCTAssertFalse(app.buttons["Good response"].exists)
        app.buttons["Bad response"].tap(); XCTAssertTrue(app.buttons["Good response"].exists)
        app.buttons["Dictate"].tap()
        XCTAssertTrue(app.buttons["Stop dictation"].waitForExistence(timeout: 3)); capture("dictation-silent")
        app.buttons["Stop dictation"].tap(); XCTAssertTrue(app.buttons["Dictate"].exists)
        app.buttons["More response actions"].tap(); capture("response-menu")
        app.buttons["Read Aloud"].tap(); XCTAssertTrue(app.buttons["Close player"].waitForExistence(timeout: 3)); capture("read-aloud")
        app.buttons["Close player"].tap()
    }
    @MainActor func testLightAndExpandedDraft() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test", "--light", "--conversation"]; app.launch()
        XCTAssertTrue(app.buttons["Good response"].waitForExistence(timeout: 5)); capture("conversation-light")
        app.terminate(); app.launchArguments = ["--ui-test", "--long-draft"]; app.launch()
        XCTAssertTrue(app.buttons["Expand composer"].waitForExistence(timeout: 5))
        XCTAssertLessThanOrEqual(app.textViews["messageComposer"].frame.height, 186)
        XCTAssertGreaterThan(app.textViews["messageComposer"].frame.height, 150)
        capture("composer-long")
        app.buttons["Expand composer"].tap()
        XCTAssertTrue(app.buttons["Collapse composer"].waitForExistence(timeout: 3)); capture("composer-expanded")
        app.buttons["Collapse composer"].tap()
        XCTAssertTrue(app.buttons["Expand composer"].waitForExistence(timeout: 3))
    }
    @MainActor private func capture(_ name: String) {
        let attachment = XCTAttachment(screenshot: XCUIScreen.main.screenshot())
        attachment.name = name; attachment.lifetime = .keepAlways; add(attachment)
    }
    @MainActor func testComposeSendCancelAndDrawer() {
        let app = XCUIApplication(); app.launchArguments = ["--ui-test"]; app.launch()
        let composer = app.textViews["messageComposer"]
        XCTAssertTrue(composer.waitForExistence(timeout: 5))
        XCTAssertEqual(app.buttons["composerPrimaryButton"].label, "Start voice")
        composer.tap(); composer.typeText("Hello")
        XCTAssertEqual(app.buttons["composerPrimaryButton"].label, "Send message")
        app.buttons["composerPrimaryButton"].tap()
        XCTAssertEqual(app.buttons["composerPrimaryButton"].label, "Stop response")
        XCTAssertTrue(app.keyboards.firstMatch.waitForNonExistence(timeout: 3))
        app.buttons["composerPrimaryButton"].tap()
        let idle = NSPredicate(format: "label == %@", "Start voice")
        expectation(for: idle, evaluatedWith: app.buttons["composerPrimaryButton"])
        waitForExpectations(timeout: 3)
        app.buttons["sidebarButton"].tap()
        XCTAssertTrue(app.buttons["Settings"].waitForExistence(timeout: 3))
        app.buttons["Settings"].tap()
        XCTAssertTrue(app.buttons["Close settings"].waitForExistence(timeout: 3))
    }
}
